In [34]:
'''
Assignment 6
A simple program in python to implement a function so that the columns of the output matrix are powers of the input
vector.
'''
import numpy as np    # importing numpy

def funcmat(N,data):     # function description to find matrix from a given vector
    print(np.dstack([x**(N-1-i) for i in range(N)]))    # np.dstack() function stacks the array column-wise

N=int(input("Enter the value of N"))    # taking value of n from user
data=np.array([2,3,4,5])    # creating a vector with 4 elements
funcmat(N,data)             # calling the function funcmat()

Enter the value of N5
[[[  1   1   1   1   1]
  [ 16   8   4   2   1]
  [ 81  27   9   3   1]
  [625 125  25   5   1]]]
